name: Analytics - Quick Start

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/ops:latest
    env:
      HOME: /home/bituser
        
    steps:
    - name: Initialize a workspace
      run: |
        bit new analytics my-analytics --env teambit.analytics/starters/analytics 
    - name: Run the app component
      run: |
        cd my-analytics
        bit run analytics &
        checkserver http://localhost:3000
    - name: Preview components
      run: |
        cd my-analytics
        bit start &
        checkserver http://localhost:3000
    - name: Collaborate
      run: |
        cd my-analytics
        bit status
    - name: Create a local scope, compile and export
      run: |
        barescope my-scope-name my-analytics
        cd my-analytics
        bit scope rename org.scope-name my-org.my-scope-name --refactor
        bit link
        bit compile
        bit tag --message "initial tag"
        bit export
    continue-on-error: false
